import type { Metadata } from "next";
import { Inter } from "next/font/google";

import StoreProvider from "@/redux/store-provider";
import { PersisterProvider } from "@/redux/persistor-provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <PersisterProvider>{children}</PersisterProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
